blox:
  world:
    pose: [0, 0, 0, 1, 0, 0, 0]
    "integrator_type": "occupancy"

cuboid:
  floor:
    dims: [10.0, 10.0, 0.1] # x, y, z
    pose: [0.0, 0.0, -0.8, 1, 0, 0, 0.0] # x, y, z, qx, qy, qz, qw
  ridgeback:  # Commented out - will be added dynamically after init
    dims: [0.8, 0.8, 0.8]
    pose: [0.0, 0.0, -0.45, 1.0, 0.0, 0.0, 0.0]
  camera_pole:
    dims: [0.1, 0.1, 3.0]
    pose: [0.0, -0.40, 0.00, 1.0, 0.0, 0.0, 0.0]